# Generated by Django 6.0.4 on 2026-04-15 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
                ('api_category_id', models.IntegerField(blank=True, null=True, verbose_name='ID категории OpenTriviaDB')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('option1', models.CharField(max_length=500, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=500, verbose_name='Вариант 2')),
                ('option3', models.CharField(max_length=500, verbose_name='Вариант 3')),
                ('option4', models.CharField(max_length=500, verbose_name='Вариант 4')),
                ('correct_option', models.IntegerField(verbose_name='Правильный вариант (1-4)')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.direction')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('correct_answers', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_spent_seconds', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.direction')),
            ],
        ),
    ]
